name: unresp
channels:
  - conda-forge
  - defaults
dependencies:
  - basemap=1.2.*
  - blas=1.0.*
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - curl=7.62.0.*
  - cycler=0.10.0.*
  - dbus=1.13.*
  - eccodes=2.12.*
  - expat=2.2.*
  - fontconfig=2.13.*
  - freetype=2.9.*
  - geos=3.7.*
  - glib=2.56.*
  - gst-plugins-base=1.14.*
  - gstreamer=1.14.*
  - hdf4=4.2.*
  - hdf5=1.10.*
  - icu=58.2.*
  - intel-openmp=2019.1.*
  - jasper=1.900.*
  - jpeg=9c.*
  - kiwisolver=1.0.*
  - libaec=1.0.*
  - libcurl=7.62.*
  - libedit=3.1.20181209
  - libffi=3.2.*
  - libgcc-ng=8.2.*
  - libgfortran=3.0.*
  - libgfortran-ng=7.3.*
  - libnetcdf=4.6.*
  - libpng=1.6.*
  - libssh2=1.8.*
  - libstdcxx-ng=8.2.*
  - libuuid=1.0.*
  - libxcb=1.13.*
  - libxml2=2.9.*
  - matplotlib=3.0.*
  - mkl=2019.1.*
  - mkl_fft=1.0.*
  - mkl_random=1.0.*
  - ncurses=6.1.*
  - numpy=1.16.*
  - numpy-base=1.16.*
  - openssl=1.1.*
  - pcre=8.43.*
  - pip=19.0.3.*
  - proj4=5.2.*
  - pyparsing=2.3.*
  - pyproj=1.9.*
  - pyqt=5.9.*
  - pyshp=2.1.*
  - python=3.6.*
  - python-dateutil=2.8.*
  - python-eccodes=2.12.*
  - pytz=2018.9.*
  - qt=5.9.*
  - readline=7.0.*
  - scipy=1.2.*
  - setuptools=40.8.*
  - sip=4.19.*
  - six=1.12.*
  - sqlite=3.27.*
  - tk=8.6.*
  - tornado=6.0.*
  - utm=0.4.*
  - wheel=0.33.*
  - xz=5.2.*
  - zlib=1.2.*
  - pip:
    - chardet==3.0.*
    - gmplot==1.2.*
    - idna==2.8.*
    - requests==2.21.*
    - urllib3>=1.26.5
